indent_style = "Block"
wrap_comments = true
format_code_in_doc_comments = true
comment_width = 100
format_strings = true
imports_layout = "Vertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_impl_items = true
